# crossword_data.py
# Large multi-topic word bank for the ZiggyBot crossword generator.
# Each entry: (ANSWER, "Clue"). Answers are A-Z only, 3-12 letters.
# Pooled across topics to give every random puzzle wide variety.

WORD_BANK = {
    "Cannabis & Culture": [
        ("INDICA", "Relaxing cannabis subspecies"),
        ("SATIVA", "Energizing cannabis subspecies"),
        ("HYBRID", "Cross of two strain types"),
        ("TERPENE", "Aromatic compound in cannabis"),
        ("EDIBLE", "Infused snack, e.g. a gummy"),
        ("ROSIN", "Solventless concentrate"),
        ("HASH", "Compressed resin product"),
        ("BUD", "Smokable flower nugget"),
        ("GRAM", "Common cannabis weight unit"),
        ("OUNCE", "Twenty-eight grams"),
        ("VAPE", "Vaporizer device, for short"),
        ("CART", "Pre-filled vape ___"),
        ("PREROLL", "Ready-to-smoke joint"),
        ("DISPENSARY", "Where cannabis is sold"),
        ("BUDTENDER", "Dispensary floor expert"),
        ("MYRCENE", "Earthy, sedating terpene"),
        ("LIMONENE", "Citrusy, uplifting terpene"),
        ("PINENE", "Pine-scented terpene"),
        ("RESIN", "Sticky trichome secretion"),
        ("KIEF", "Sifted trichome powder"),
        ("GELATO", "Dessert-named popular strain"),
        ("GASSY", "Diesel-like aroma descriptor"),
        ("POTENT", "High in active compounds"),
        ("AROMA", "Distinctive smell"),
        ("HARVEST", "Time to cut the crop"),
    ],
    "Science & Nature": [
        ("ATOM", "Basic unit of matter"),
        ("CELL", "Smallest unit of life"),
        ("ENZYME", "Biological catalyst"),
        ("GRAVITY", "Force that pulls objects down"),
        ("OXYGEN", "Gas we breathe"),
        ("CARBON", "Element with symbol C"),
        ("PHOTON", "Particle of light"),
        ("NEURON", "Nerve cell"),
        ("GENOME", "Full set of genes"),
        ("ORBIT", "Path around a planet"),
        ("COMET", "Icy body with a tail"),
        ("PLANET", "Earth or Mars, e.g."),
        ("FOSSIL", "Preserved ancient remains"),
        ("MAGMA", "Molten underground rock"),
        ("FUNGUS", "Mushroom kingdom member"),
        ("POLLEN", "Flower's fine powder"),
        ("TIDE", "Ocean's rise and fall"),
        ("ECHO", "Reflected sound"),
        ("PRISM", "Light-splitting glass"),
        ("LASER", "Focused beam of light"),
        ("VOLT", "Unit of electric potential"),
        ("ACID", "Low-pH substance"),
        ("SOLAR", "Relating to the sun"),
        ("LUNAR", "Relating to the moon"),
        ("SPECIES", "Biological classification group"),
    ],
    "Geography": [
        ("RIVER", "Flowing waterway"),
        ("DESERT", "Arid sandy region"),
        ("ISLAND", "Land surrounded by water"),
        ("VALLEY", "Low land between hills"),
        ("CANYON", "Deep river-carved gorge"),
        ("GLACIER", "Slow-moving ice mass"),
        ("VOLCANO", "Erupting mountain"),
        ("PRAIRIE", "Flat grassland"),
        ("HARBOR", "Sheltered port"),
        ("PLATEAU", "Elevated flatland"),
        ("EUROPE", "Continent west of Asia"),
        ("AFRICA", "World's second-largest continent"),
        ("BRAZIL", "Largest South American country"),
        ("EGYPT", "Land of the pyramids"),
        ("JAPAN", "Island nation, land of the rising sun"),
        ("PARIS", "City of Light"),
        ("TOKYO", "Japan's capital"),
        ("DENVER", "Mile-High City"),
        ("ALASKA", "Largest U.S. state"),
        ("NEVADA", "Silver State"),
        ("OASIS", "Desert water source"),
        ("DELTA", "River mouth landform"),
        ("REEF", "Coral ridge near shore"),
        ("TUNDRA", "Frozen treeless plain"),
        ("LAGOON", "Shallow coastal lake"),
    ],
    "Food & Drink": [
        ("PASTA", "Italian noodle dish"),
        ("CHEESE", "Cheddar or brie"),
        ("TOMATO", "Pizza sauce base"),
        ("GARLIC", "Pungent cooking bulb"),
        ("PEPPER", "Spicy or bell variety"),
        ("HONEY", "Bee-made sweetener"),
        ("MANGO", "Tropical orange fruit"),
        ("LEMON", "Sour yellow citrus"),
        ("COCOA", "Chocolate's source"),
        ("COFFEE", "Morning caffeine fix"),
        ("BAGEL", "Ring-shaped bread"),
        ("WAFFLE", "Gridded breakfast treat"),
        ("BUTTER", "Toast spread"),
        ("PICKLE", "Brined cucumber"),
        ("NOODLE", "Ramen strand"),
        ("SALSA", "Chip dip"),
        ("TACO", "Folded Mexican dish"),
        ("SUSHI", "Rice-and-fish roll"),
        ("BROTH", "Soup base liquid"),
        ("YOGURT", "Cultured dairy snack"),
        ("OLIVE", "Martini garnish"),
        ("CIDER", "Pressed apple drink"),
        ("WALNUT", "Brain-shaped nut"),
        ("RAISIN", "Dried grape"),
        ("BISCUIT", "Flaky baked side"),
    ],
    "Animals": [
        ("TIGER", "Striped big cat"),
        ("EAGLE", "Soaring bird of prey"),
        ("DOLPHIN", "Clever marine mammal"),
        ("PYTHON", "Constricting snake"),
        ("FALCON", "Fast-diving raptor"),
        ("BEAVER", "Dam-building rodent"),
        ("RABBIT", "Hopping long-eared pet"),
        ("PENGUIN", "Tuxedoed flightless bird"),
        ("GIRAFFE", "Long-necked grazer"),
        ("OCTOPUS", "Eight-armed sea creature"),
        ("LIZARD", "Cold-blooded reptile"),
        ("SALMON", "Upstream-swimming fish"),
        ("TURTLE", "Shelled reptile"),
        ("HORNET", "Large stinging wasp"),
        ("COYOTE", "Wild canine of the West"),
        ("OTTER", "Playful river swimmer"),
        ("MOOSE", "Antlered northern giant"),
        ("BISON", "American plains grazer"),
        ("HERON", "Long-legged wading bird"),
        ("GECKO", "Wall-climbing lizard"),
        ("CAMEL", "Humped desert traveler"),
        ("PANDA", "Bamboo-eating bear"),
        ("ZEBRA", "Striped African equine"),
        ("RAVEN", "Glossy black corvid"),
        ("FERRET", "Slinky weasel relative"),
    ],
    "Music & Arts": [
        ("GUITAR", "Six-stringed instrument"),
        ("PIANO", "88-key instrument"),
        ("VIOLIN", "Bowed string instrument"),
        ("DRUM", "Percussion instrument"),
        ("MELODY", "Tune you can hum"),
        ("RHYTHM", "Musical beat pattern"),
        ("CHORD", "Three or more notes together"),
        ("TEMPO", "Speed of a piece"),
        ("OPERA", "Sung dramatic work"),
        ("CANVAS", "Painter's surface"),
        ("SCULPT", "Shape from clay or stone"),
        ("PALETTE", "Painter's color board"),
        ("MURAL", "Wall painting"),
        ("SONNET", "14-line poem"),
        ("BALLET", "Classical dance form"),
        ("LYRIC", "Song's words"),
        ("BANJO", "Twangy folk instrument"),
        ("FLUTE", "Woodwind you blow across"),
        ("TRUMPET", "Brass instrument with valves"),
        ("ENCORE", "Crowd-demanded repeat"),
        ("STUDIO", "Where albums are recorded"),
        ("REMIX", "Reworked track"),
        ("VINYL", "Old-school record format"),
        ("CHOIR", "Group of singers"),
        ("SOLO", "Performed alone"),
    ],
    "Sports & Games": [
        ("SOCCER", "World's most popular sport"),
        ("TENNIS", "Racket sport with love scores"),
        ("HOCKEY", "Puck-and-stick sport"),
        ("BOXING", "Gloved ring sport"),
        ("SKIING", "Downhill snow sport"),
        ("ROWING", "Crew team sport"),
        ("RACKET", "Tennis or squash tool"),
        ("HELMET", "Protective headgear"),
        ("REFEREE", "Game official"),
        ("STADIUM", "Big sports venue"),
        ("MARATHON", "26.2-mile race"),
        ("HURDLE", "Track-and-field barrier"),
        ("DRIBBLE", "Bounce the basketball"),
        ("INNING", "Baseball segment"),
        ("PUTTER", "Golf green club"),
        ("CHESS", "Game of kings and pawns"),
        ("POKER", "Bluffing card game"),
        ("DOMINO", "Tile with dots"),
        ("ARENA", "Indoor sports hall"),
        ("MEDAL", "Olympic award"),
        ("UMPIRE", "Baseball official"),
        ("RALLY", "Long tennis exchange"),
        ("SPRINT", "Short fast race"),
        ("ANGLER", "Fishing hobbyist"),
        ("PADDLE", "Canoe or pingpong tool"),
    ],
    "Everyday & Misc": [
        ("PILLOW", "Bed head cushion"),
        ("WINDOW", "Glass wall opening"),
        ("CANDLE", "Wax light source"),
        ("WALLET", "Cash and card holder"),
        ("UMBRELLA", "Rain shield"),
        ("LADDER", "Climbing rungs"),
        ("MIRROR", "Reflective glass"),
        ("BASKET", "Woven carrier"),
        ("BUTTON", "Shirt fastener"),
        ("PENCIL", "Erasable writer"),
        ("CLOCK", "Time teller"),
        ("BRIDGE", "River-spanning structure"),
        ("ENGINE", "Car's power plant"),
        ("ROCKET", "Space launch vehicle"),
        ("ANCHOR", "Ship's holding weight"),
        ("LANTERN", "Portable light"),
        ("KETTLE", "Water boiler"),
        ("BLANKET", "Bed cover"),
        ("DRAWER", "Sliding storage box"),
        ("HAMMER", "Nail driver"),
        ("WRENCH", "Bolt turner"),
        ("COMPASS", "Direction finder"),
        ("TICKET", "Admission slip"),
        ("PUZZLE", "Brain-teasing challenge"),
        ("MARKET", "Place to buy and sell"),
    ],
    "Tech & Words": [
        ("SERVER", "Data-hosting computer"),
        ("PIXEL", "Screen dot"),
        ("BINARY", "Ones-and-zeros code"),
        ("CURSOR", "On-screen pointer"),
        ("LAPTOP", "Portable computer"),
        ("ROUTER", "Wi-Fi distributor"),
        ("BROWSER", "Web-viewing program"),
        ("KEYBOARD", "Typing device"),
        ("BACKUP", "Saved copy of data"),
        ("UPLOAD", "Send a file to the cloud"),
        ("STREAM", "Watch online in real time"),
        ("WIDGET", "Small app element"),
        ("FOLDER", "File container"),
        ("GADGET", "Handy device"),
        ("CIRCUIT", "Electrical loop"),
        ("BATTERY", "Power storage cell"),
        ("SCREEN", "Display surface"),
        ("CODE", "Programmer's text"),
        ("DATA", "Information set"),
        ("MODEM", "Internet connector"),
        ("CLOUD", "Online storage, broadly"),
        ("ICON", "Clickable little image"),
        ("CABLE", "Connecting wire"),
        ("DRONE", "Flying camera craft"),
        ("ROBOT", "Automated machine"),
    ],
    "History & People": [
        ("EMPIRE", "Vast ruled territory"),
        ("CASTLE", "Medieval fortress"),
        ("KNIGHT", "Armored warrior"),
        ("PHARAOH", "Egyptian ruler"),
        ("TEMPLE", "Place of worship"),
        ("PYRAMID", "Egyptian tomb shape"),
        ("VIKING", "Norse seafarer"),
        ("SAMURAI", "Japanese warrior"),
        ("THRONE", "Royal seat"),
        ("LEGEND", "Storied tale or hero"),
        ("COMPASS", "Explorer's navigation tool"),
        ("VOYAGE", "Long sea journey"),
        ("TREATY", "Peace agreement"),
        ("ARMOR", "Battle protection"),
        ("SCROLL", "Rolled ancient document"),
        ("CHARIOT", "Ancient horse cart"),
        ("DYNASTY", "Ruling family line"),
        ("MUSEUM", "History display hall"),
        ("RELIC", "Ancient artifact"),
        ("EXPLORE", "Seek the unknown"),
    ],
}


def get_flat_word_list():
    """Return a flat list of (ANSWER, clue) with duplicates removed by answer."""
    seen = set()
    flat = []
    for topic, pairs in WORD_BANK.items():
        for ans, clue in pairs:
            a = ans.upper().strip()
            if a.isalpha() and 3 <= len(a) <= 12 and a not in seen:
                seen.add(a)
                flat.append((a, clue))
    return flat
