SUPABASE_URL = "https://zorfzlsixtmrxaaitpyt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvcmZ6bHNpeHRtcnhhYWl0cHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxNjQ5ODEsImV4cCI6MjEwNTc0MDk4MX0.iVSNJ2Ee7AB5xTf3QFKTNEzczqV8aET-J5SxPf3xd6c"
